front_page:
    path:      /
    defaults:  { _controller: PutrCliRtvSloParserBundle:Default:index }

feed_dnevnik:
    path:      /rss/{source}
    defaults:  { _controller: PutrCliRtvSloParserBundle:Default:feed }

sonata_page_cache:
    resource: '@SonataCacheBundle/Resources/config/routing/cache.xml'
    prefix: /