parameters:
#

services:

    rtv.scraper:
      class: Putr\Cli\RtvSloParserBundle\Service\RTV
      arguments: [@logger, @service_container]
      tags:
            - { name: monolog.logger, channel: videoRTVService }

    rtv.twitter.dnevnik:
      class: Putr\Cli\RtvSloParserBundle\Service\Twitter
      arguments: [@logger, @service_container]
      tags:
            - { name: monolog.logger, channel: twitterService }

    dnevnik.rss:
      class: Putr\Cli\RtvSloParserBundle\Service\RSS
      arguments: [@logger, @service_container]
      tags:
            - { name: monolog.logger, channel: rssService }

    scraper_worker:
      class: Putr\Cli\RtvSloParserBundle\Consumer\ScraperWorkerConsumer
      arguments: [@logger, @service_container]
      tags:
            - { name: monolog.logger, channel: scraperWorker }
